name: Deploy Hugo site to GitHub Pages

on:
  push:
    paths:
      - 'website/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: true  # If you use Hugo themes as submodules
          fetch-depth: 0

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Clean public directory
        run: rm -rf website/public

      - name: Build Hugo site
        run: hugo --source website --destination public --baseURL "https://cf-purge.app"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/public
          publish_branch: gh-pages
          force_orphan: true
