# .github/workflows/release.yaml

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          binary_name: 'cf-purge'
          release_tag: 'v0.0.1'
          release_name: 'v0.0.1'
